/**
 * @name LastMessageDateUserSearch
 * @author cypher139
 * @authorId 340558434963292160
 * @version 1.0
 * @description Fork of LastMessageDate by DevilBro to find any missing Last sent Message Dates for users in cypher139's DiscordBot Leaderboard system. To use, place config file generated by DiscordBot in the plugins folder, restart Discord, then just navigate through servers and channels; Periodically we'll search for a handful of message dates.
 * @invite R97tm9M
 * @donate https://www.paypal.me/CypherNova139
 * @website https://github.com/cypher139
 * @source https://github.com/cypher139/ch/tree/release/dev/DiscordBot
 * @updateUrl https://github.com/cypher139/ch/raw/refs/heads/release/dev/DiscordBot/experimental.library/LastMessageDateUserSearch.plugin.js
 */

module.exports = (_ => {
	const changeLog = {
		
	};

	return !window.BDFDB_Global || (!window.BDFDB_Global.loaded && !window.BDFDB_Global.started) ? class {
		constructor (meta) {for (let key in meta) this[key] = meta[key];}
		getName () {return this.name;}
		getAuthor () {return this.author;}
		getVersion () {return this.version;}
		getDescription () {return `The Library Plugin needed for ${this.name} is missing. Open the Plugin Settings to download it. \n\n${this.description}`;}
		
		downloadLibrary () {
			BdApi.Net.fetch("https://mwittrien.github.io/BetterDiscordAddons/Library/0BDFDB.plugin.js").then(r => {
				if (!r || r.status != 200) throw new Error();
				else return r.text();
			}).then(b => {
				if (!b) throw new Error();
				else return require("fs").writeFile(require("path").join(BdApi.Plugins.folder, "0BDFDB.plugin.js"), b, _ => BdApi.UI.showToast("Finished downloading BDFDB Library", {type: "success"}));
			}).catch(error => {
				BdApi.UI.alert("Error", "Could not download BDFDB Library Plugin. Try again later or download it manually from GitHub: https://mwittrien.github.io/downloader/?library");
			});
		}
		
		load () {
			if (!window.BDFDB_Global || !Array.isArray(window.BDFDB_Global.pluginQueue)) window.BDFDB_Global = Object.assign({}, window.BDFDB_Global, {pluginQueue: []});
			if (!window.BDFDB_Global.downloadModal) {
				window.BDFDB_Global.downloadModal = true;
				BdApi.UI.showConfirmationModal("Library Missing", `The Library Plugin needed for ${this.name} is missing. Please click "Download Now" to install it.`, {
					confirmText: "Download Now",
					cancelText: "Cancel",
					onCancel: _ => {delete window.BDFDB_Global.downloadModal;},
					onConfirm: _ => {
						delete window.BDFDB_Global.downloadModal;
						this.downloadLibrary();
					}
				});
			}
			if (!window.BDFDB_Global.pluginQueue.includes(this.name)) window.BDFDB_Global.pluginQueue.push(this.name);

		}
		start () {this.load();}
		stop () {}
	} : (([Plugin, BDFDB]) => {
		var _this;
		var loadedUsers, requestedUsers, queuedInstances;
		var currentPopout, currentProfile;
		var lastRun;
		
		function UserSearch () {
			let searchresults = {};
			let searchCount = 0;
			let currentGuildID = BdApi.Webpack.getStore("SelectedGuildStore").getGuildId();
			const allGuilds = BdApi.Webpack.getStore("GuildStore").getGuildIds();
			// Await Rate Limits
			if ((lastRun + 300000) > Date.now()) {
				BdApi.UI.showToast("Currently waiting 5 minutes before we search again.", {type: "info"});
				console.log(`Last run: ${lastRun}`);
				console.log(`current: ${Date.now()}`);
				return null;
			}
			searchresults = BdApi.Data.load("LastMessageDateUserSearch", "all");
			if (searchresults["servers"] === undefined) {
				BdApi.UI.showToast("No servers are setup to search Message Dates for! Add the config file from DiscordBot into the plugins folder, and then try again.", {type: "error"});
				return null;
			}
			if (searchresults["servers"][currentGuildID] === undefined) {
				BdApi.UI.showToast("Currently selected server is not listed in search config.", {type: "info"});
				// return null;
			}
			for (let guildID of Object.keys(searchresults["servers"])) {
				if (!loadedUsers[guildID]) loadedUsers[guildID] = {};
				if (!requestedUsers[guildID]) requestedUsers[guildID] = {};
				if (!queuedInstances[guildID]) queuedInstances[guildID] = {};
				// Check if user in guild, continue if not found
				if (!allGuilds.includes(guildID)) { 
					BdApi.UI.showToast(`You are not a member of the ${guildID} server!`, {type: "error"});
					continue;
				}
				//Get IDs
				for (let [userID, userDate] of Object.entries(searchresults["servers"][guildID])) {
					//Rate limiting
					if (searchCount > 5) {
						lastRun = Date.now();
						break;
					}
					if (userDate > 1) { continue; }
					console.log(`Check: ${userID}: ${userDate}`);
					console.log(loadedUsers);
					if (loadedUsers[guildID][userID] === undefined && !requestedUsers[guildID][userID]) {
						console.log(`${guildID}: ${userID}: Loading Messages`);
						requestedUsers[guildID][userID] = true;
						queuedInstances[guildID][userID] = [].concat(queuedInstances[guildID][userID]).filter(n => n);
						BDFDB.LibraryModules.HTTPUtils.get({
							url: BDFDB.DiscordConstants.Endpoints.SEARCH_GUILD(guildID),
							query: BDFDB.LibraryModules.APIEncodeUtils.stringify({
								author_id: userID,
								include_nsfw: true
							})
						}).then(result => {
							delete requestedUsers[guildID][userID];
							// console.log(JSON.stringify(result.body.messages));
							if (typeof result.body.retry_after != "number") {
								if (result.body.messages && Array.isArray(result.body.messages[0])) {
									for (let message of result.body.messages[0]) if (message.hit && message.author.id == userID) loadedUsers[guildID][userID] = message;
								}
								// else loadedUsers[guildID][userID] = null;
								BDFDB.ReactUtils.forceUpdate(queuedInstances[guildID][userID]);
								delete queuedInstances[guildID][userID];
							}
							else BDFDB.TimeUtils.timeout(_ => BDFDB.ReactUtils.forceUpdate(this), result.body.retry_after + 500);
						BdApi.UI.showConfirmationModal("Last Message Date User Search", `${userID}: ${loadedUsers[guildID][userID]["author"]["username"]}: ${loadedUsers[guildID][userID]["content"]}`);
						BdApi.UI.showToast(`${userID}: ${loadedUsers[guildID][userID]["author"]["username"]}: ${loadedUsers[guildID][userID]["content"]}`, {type: "info"});
						searchresults["servers"][guildID][userID] = loadedUsers[guildID][userID]["id"];
						});
					}
					// console.log(loadedUsers);
					// console.log(JSON.stringify(loadedUsers[guildID][userID]["id"]));
					// if (loadedUsers[guildID][userID] === undefined) {
						// if (queuedInstances[guildID][userID].indexOf(this) == -1) queuedInstances[guildID][userID].push(this);
						// return null;
					// }
					// console.log(searchresults);
					// searchresults["servers"][guildID][userID] = loadedUsers[guildID][userID]["id"];
					searchCount++;
				}
			}
			console.log(`Stage 2 : Finished ${searchCount} searches`);
			// Save found ids
			if (searchCount > 0) {
				// console.log("searchsave");
				// Check each entry for non-zero. set flag and continue if a zero is found.
				let foundZero = false;
				for (let guildID of Object.keys(searchresults["servers"])) {
					for (let [userID, userDate] of Object.entries(searchresults["servers"][guildID])) {
						if (userDate < 1) { 
							foundZero = true;
							break;
						}
					}
				}
				
				if(!foundZero) {
					BdApi.UI.showConfirmationModal("Last Message Date User Search", `Stage 2 of 3 Complete: Saved all listed message dates! Transfer the config file back to DiscordBot Logs folder and run the import command to save the dates into the leaderboard.`);
				}
				BdApi.Data.save("LastMessageDateUserSearch", "all", searchresults);
				// console.log(searchresults);
				// console.log(loadedUsers);
			}
		}
		
		return class LastMessageDateUserSearch extends Plugin {
			onLoad () {
				_this = this;
				loadedUsers = {};
				requestedUsers = {};
				queuedInstances = {};
				// this.defaults = {
					// servers: {},
				// };
				this.patchPriority = 9;
			}
			onSwitch() {
				let currentGuildID = BdApi.Webpack.getStore("SelectedGuildStore").getGuildId();
				//null = DMs
				if (currentGuildID === null) { return null; }
				let currentChannelID = BdApi.Webpack.getStore("SelectedChannelStore").getChannelId();
				console.log(`switched: ${currentGuildID} : ${currentChannelID}`);
				UserSearch(currentGuildID);
			}
		};
	})(window.BDFDB_Global.PluginUtils.buildPlugin(changeLog));
})();
