# discordBot Guild Configuration
# General admin
Server_Nickname: "Your Server"
#
# Logs:
# Log channel for misc. messages, such as Discord command usage, LB level updates, MC server silent admin joins, Bot DM messages, etc.
Log_Channel: bot-logs
# Your server's main logs channel. Member join / invite used messages are sent here.
Server_Log_Channel: bot-logs
# Your server's announcements channel. Anti Spam general alerts are sent here.
Announcement_Channel: announcements
# Send message to Console: Includes logs such as Member joins, voice chat joins, Bot DM notifications, and Discord Command usage.
# Note: Error messages are always sent.
Console_Messages: true
# Send Chat messages to Console:
Console_Messages_Chat: false
# Send Bot debug messages for events that occur regarding this server?
Console_Debug: false
# Send a message to log on Member join with the invite used?
Log_Invites: true
# Customize Member join log message sent: 
# Variables: %User%  %UserID%  %InviteCode%  %Uses%  %Inviter%  %InviterID%  %InviterID1%
# %InviterID1% shows the inviter's ID if first time using invite.
Log_Invites_Message: "**%User%**  [%UserID%] joined using invite **%InviteCode%**\n `Invite: -Use #%Uses%  -From: %Inviter% %InviterID%`"
# Show Bot DM Notifications:
DM_Notify: true
# Show Bot DM notification if the user is *not* a server member?
DM_Notify_NonMember: false

#todo
Minecraft_Messages_Admin: true
#
#
# Anti Spam
# When a member joins, how much time elapses before Anti spam no longer considers them a new join? (in millseconds)
AS_New_User_Time: 600000000
# How many different channels can a new user post on, before Anti Spam considers them to be a spammer?
AS_New_User_Channel_Limit: 7
# If a user triggers Anti Spam, delete their most recent messages?
AS_Delete_Messages: true
# Log various User Info in the Spam alert message?
AS_Log_ShowUserInfo: true
#General Alert to all server members. Useful to tell users to keep their accounts safe, and to inform users of why many channels may have missing unread messages.
AS_General_Announcement: "Another member got hacked or just chose to spam sketchy invites. I removed those messages, sorry for the unread notifications! Remember if you get your account back feel free to DM one of us or someone from the server so that you can be unbanned."
# Showcase Channel
# Intended as a place to show your server community's art projects, latest game achievements, etc., and ward off chat to another channel.
# To enable the Showcase channel chat protection feature place the channel's ID below:
Showcase_Channel: 123235346
#What channel should users be redirected to if they are talking about project?
Showcase_Channel_Talk: 987654213
# What replies should we say to users who were chatting?
Showcase_Reactions:
  # Chat was not allowed, as it did not fit the posting requirements
  Not_Allowed: "To show your cool project please include a picture!\n To react, add a reaction and talk in %TalkChannel%"
  # Previous message already is a comment from same poster
  Multiple_Msgs: "%UserID% To include more details about your project please edit the additional info into your previous post."
  # Chat was a reaction from another user
  Reaction_Comment: "Thanks for your comment %UserID%! To avoid chat in the showcases, **add a reaction** to the original post and **talk in %TalkChannel%** about the showcased project!"
#
#
# Mentions
Sanitize_Mentions:
# Replaces subject with a replacement
  hey: "Hey"
#
#
#Chat
# If a URL is sent in the message should Minecraft players see the full URL? Applies to Discord message attachments.
URL_Broadcast: false
# All roles to be considered as an Admin on your server place here:
Role_Admins:
- Owner
- Co-Owner
- "Server Admin"
#customizes the name color sent for messages to the Minecraft server, for users with a matching role.
# Role Name: hexadecimal color code
Role_Colors:
  Active Level 1: f1c40f
  Active Level 2: f1c40f
  Active Level 3: f1c40f
  Co-Owner: 1bae93
  Purple: 8a00ff
  Member: 7289da
  Most Active: f1c40f
  Owner: fbff00
  Server Admin: ba3e39
# Shall we receive messages from Minecraft players in your server's designated Minecraft channel?
Minecraft_Messages: true
# Shall we receive messages from other Discord server's Minecraft channels in your server's designated Minecraft channel?
Cross_Server_Messages: true
# Which channels are allowed to send messages to the Minecraft server? (Applies only if your server is the bot's Primary Guild!)
Channels_Receive:
- general
- default
- news
- minecraft
- voice-chat
- other
# Which channels are allowed to receive messages from Minecraft players?
Channels_Send:
- general
- minecraft
- suggestions
- voice-chat
- other
- botspam
# Default Minecraft server channel. All Minecraft player messages, death messages, join/leave messages are sent here.
Minecraft_Channel: minecraft
Default_Channel: minecraft
# Should we Convert emoji markdown into actual emoji?
Use_Emojis: true
# Should we only convert emoji if the emoji is from your server?
Use_Other_Emojis: true
#
# Cross Server Options:
# Prefix user to the beginning of message, if false prefixes server name instead.
CS_Prefix_User: true
# Limit prefix to 1 letter
CS_Prefix_Limit: true
# Allow mention of username?
# Note: Roles and everyone/here won't be mentioned.
CS_Mention_User: true
# If the message provides a referenced message, show referenced message in an embed?
CS_Show_Reference: true
# Show URL links to attached files?
CS_URL_Broadcast: true
#
#
# Commands
# Allow the bot to listen to commands issued from your server?
# -- Slash commands not supported, only prefix.
CMD_Enable: true
# What prefix should trigger the bot commands? (Uses RegEx)
# Example prefixes:
# -- Prefix 2 letters with ! at start or end. also supports no space between command and prefix
#                    "^(?:[?!%/.$,=]+[Cc][Hh](?!$)[?!%/.$,=]*|[Cc][Hh][?!%/.$,=]+)"
# -- Use just a symbol prefix:
#                    "^\\s*[?!%/.$,=]+\\s*(?!$)"
CMD_Command_Prefix: "^\\s*[?!%/.$,=]+\\s*(?!$)"
# Which channels are allowed to receive command messages from Discord users?
CMD_Channels_Receive:
- general
- default
- off-topic
- minecraft
- voice-chat
- other
- botspam
# Which channels are allowed to receive command message replies?
CMD_Channels_Send:
- general
- minecraft
# Default channel to use bot commands in, usually a "botspam" channel meant to keep spam away from other channels.
CMD_Default_Channel: botspam
# What should the bot do with the originating command message?
# "delete" to delete the message, "reply" to reference to message in command reply
CMD_Message_Action: reply
# How many arguments should we display in log messages? (Full args list can be viewed via internal ram logs)
CMD_Args_Display_Limit: 5
# Message User if the command is not found?
# "true" to always message, "false" to not message, "repeat" to only message if the command is tried twice.
CMD_Not_Found_Message_Action: repeat

#
# Command Options
# Command: fakeadmin
# What role do you use to award as a joke / fake Admin role? (DO NOT give a real admin role here)
Fake_Admin_Role: 123456
Fake_Admin_Rolename: "Super Admin"
# Command: mc-whitelist
# Which role on your server is allowed to whitelist Minecraft players on the Minecraft server? (uses a Role ID)
Whitelist_Role: 123456
# How many whitelists are allowed per player? (If no limit desired set to a high number)
Whitelist_Allowed_Uses: 5
#
#
#Admin
#Send Message edited logs to server log channel?
Log_Message_Edit: false
#Send a reply to the user who edited their message? (only replies to thsoe listed below)
Reply_Message_Edit: true
# List of users to reply to and the message to reply with
Reply_Message_Edit_Users:
  Username: "Thanks for that message edit!"
# Apply a random chance of replying, or not replying to message? Higher numbers give a lesser chance.
# Comment the line out to reply to every message edit.
# Reply_Message_Edit_Random: 14
#
#
#Voice Chat
VC_Options:
  # Type your Voice Channel's ID here: 
  987654321:
# Voice Chat Accompanying text channel ID. (Right click channel, Copy ID)
# This channel will have the ping message placed here.
# If you are using the built in text channel, use the same ID as your voice channel.
    VC_Text_Channel_ID: 123456789
# Voice Chat Role's ID. (Mention role in a message with a \ before the mention to get the ID)
# This is the role to ping to notify other fellow chatters to come chat.
    VC_Role_ID: 123
# Voice Chat Role name. Case sensitive!
# This is the role to ping to notify other fellow chatters to come chat.
    VC_Role_Name: VC
# Voice Chat Channel's ID. (Right click channel, Copy ID)
    # VC_Channel_ID: 987654321
# Voice Chat Channel's name. Case sensitive!
    # VC_Channel_Name: General
# Server Logs:
# Uncomment log types to show that type in your server log channel.
    VC_Logs:
    - Join
    - Leave
    - Completed
# Ping Timeout
# How long (in milliseconds) should we wait before performing another ping?
# Default: 12 hours = 43200000
    VC_Ping_Timeout: 43200000
    VC_Ping_If_Role_Member: true
    VC_Ping_Min_Member: 2
# Ping Message
# What should we say to the Discord members?
# Variables: %Channel%  %UserID%  %RoleID%
    VC_Ping_Message: "We are Live in %Channel% with %UserID%, come join! %RoleID%"
# What should we say to the Minecraft server players?
# Variables: %User% %Channel%
    VC_Ping_Message_MC: "%User% is ready to voice chat on the Discord!!"
# What should we say to thank all the users who chatted in completed VC call??
    VC_DM_Thanks: false
# DM the VC ping role users?
    VC_DM_VC_Role: false
    VC_DM_Thanks_Message: "Thanks %User% for joining the voice chat today! See you again soon next time we are online and chatting!"
#
#
# Discord New Member welcome
# Welcome Message channel. Case sensitive!
# This channel will have the Welcome message placed here.
Welcome_Text_Channel_Name: general
# Voice Chat text Channel ID. (Right click channel, Copy ID)
Welcome_Text_Channel_ID: 123456789
# What roles, if any, do new joins need to be equipped with?
# Only role IDs are supported.
Welcome_Roles_Award: false
Welcome_Roles:
- 123
- 456
# If a previous member rejoins, restore their roles they had?
Welcome_Roles_Restore: true
# Ping Timeout
# How long (in milliseconds) should we wait before we don't delete the welcome message on new joiner's leave?
# Default: 4 days hours = 345600000
Welcome_Message_Timeout: 345600000
# What should we say to the new Discord members?
Welcome_Send_Message: true
Welcome_Message: "Welcome %UserID% to *our server*! \n Come introduce yourself by chatting below."
# What should we DM the new Discord member?
Welcome_Send_DM: false
Welcome_DM_Message: "Welcome to *our server*! \n\n We would like to get to know you! Come introduce yourself in the %WelcomeChannel% channel."
#
#
# Leaderboards
# -- This awards 'XP' on each message sent, earn enough XP and a user can rank up to next rank acquiring a new rank role!
# -- Useful for unlocking server channels after so many messages sent, etc.
#
# Use the Leaderboard feature?
LB_Enable: true
LB_Options:
  Guild_Name: test123
  # Remove leaderboard entry on Member leave?
  Remove_On_Leave: true
  # XP earn type: Use 0 for Mee6's XP formula, use 1 for Cypher139's reimplementation.
  XP_Type: 1
  # Each message will earn a random amount of XP between the first and second number below:
  XP_Per_Message:
  - 15
  - 25
  # XP multiplier
  XP_Gain_Rate: 1
# Role Rewards: when a user reaches a certain rank number, the corresponding role is given to them. 
# -- This is typically used to award a "member" status to users who have chatted a lot.
# -- Useful for unlocking server channels for those who have been on server for a long time, etc.
  Role_Rewards:
    #Format:
    #
    # Rank Number:
    #   Role ID number:
    #   Role Name:
    1:
      RoleID: 123
      RoleName: Newbie
    10:
      RoleID: 234
      RoleName: "Active Level 1"
    20:
      RoleID: 345
      RoleName: "Active Level 2"
    30:
      RoleID: 456
      RoleName: "Active Level 3"
    50:
      RoleID: 567
      RoleName: "Most Active"
    5:
      RoleID: 678
      RoleName: Member
# Allow User's Role Rewards to stack, or only keep the highest rank?
  Stack_Role_Rewards: false
#
# Level Up Messaging:
# - Customize message sent upon leveling up to a new rank level number
# variables: %UserID%  %Level%  %MsgCount%  %LevelDisplay%
# %LevelDisplay% changes from "Level (level number)" to "Rank Name! (level number)" if a rank is awarded.
  Level_Up_Message: "%UserID% just leveled up to %Level%"
# - Level up message type: Set to true for current channel, false to disable, log to send to log channel, dm to dm user instead
  Level_Up_Announce: true
# - Only Start announcing when level reaches this start threshold:
  Level_Up_Announce_Start: 0
  Level_Up_Announce_End: 50
# - Only announce Level Up if there is a Role Rewards Rank change?
  Level_Up_Announce_OnlyReward: true
# - Reference the message that triggered a Level Up message?
  Level_Up_Announce_Reference: true
# If a message is sent in these channels, do NOT count it towards XP earning.
  NoXP_Channels:
  - 'botspam'
  - 'join-log'
# If a user sends a message while having one of these roles, do NOT count it towards XP earning.(role IDs only)
  NoXP_RoleID:
  - 123
  - 456
# Active User:
# Gives a role to users who have sent a message in the last 60 days.
# -- With proper role display formatting, this is intended to clean up the online users sidebar to those who are active ins erver, rather than those who have higher roles.
  Use_Active_User_Role: false
  # Type the role ID of the role to give active users:
  Active_User_Role: 070
  # Only start awariding the Active user role if the user has at least this much rank on the leaderboard.
  # -- Set to at least 1 to avoid giving the active user role out immediately to new joiners.
  Active_User_Role_Min_Level: 1
#
#
#
# Role Ranks
# -- This feature automatically awards a "Rank Role" if a user obtains a certain amount of tracked roles.
# -- Example: User has "PS1 Game Console" and "PS2 Game Console" roles on your server, both roles are listed, Rank Role "2" is "Multiple Game Consoles": user receives Rank Role "Multiple Game Consoles" for having 2 tracked roles.
# Use the Role Ranks feature?
Use_Role_Ranks: false
# If you use separator roles to group role displays, those separator roles can be given automatically if user obtains at least 1 rank role.
Use_Role_Ranks_Separators: false
Role_Ranks:
    #Format:
    #
    # Number of tracked roles User needs:
    #   Rank Role ID number:
    #   Rank Role Name:
  1:
    RoleID: 123
    RoleName: "rank 1"
  2:
    RoleID: 234
    RoleName: "rank 2"
  4:
    RoleID: 345
    RoleName: "rank 4"
  9:
    RoleID: 999
    RoleName: "rank 9"
# Only these roles listed count towards obtaining a ranked role. (Role IDs only)
Role_Ranks_Qualifying_Roles:
- 123456
- 452255
- 825431
- 712202
- 452070
# If a user does NOT have a listed tracked role below, then check if an additional role is present.
Role_Ranks_QR_Bonus:
# Format:
# Unobtained Role ID: Check this Role ID
  452070: 573978
#List your separator roles, used to group roles in role display. (Role IDs only)
Role_Ranks_Separators:
- 822679
- 822680
# If needed, list User and Role IDs below that need to be ignored by the rank system.
Role_Ranks_IgnoreAdmin: false
Role_Ranks_IgnoreUser:
- 98765432
Role_Ranks_IgnoreRole:
- 98765432
#
#
# Role Groups
# Have certain sub roles that count under a specific category role? group them here for use in member directory features
# Format: Role Name: Group Role