# General admin
Console_Receive_Msgs: false
Log_Invites: true
Log_Invites_Message: "**%User%**  [%UserID%] joined with invite **%InviteCode%** *(use #: %Uses%)* \n `Invite from: %Inviter% [ID: %InviterID%]`"
Log_Channel: bot-logs
Server_Log_Channel: bot-logs
Showcase_Channel: 123235346
DM_Notify: true
#
#
# Mentions
Banned_Mentions:
- "@everyone"
- "@here"
Message_On_Mention: true
Kick_On_Mention: true
Ban_On_Repeat_Mention: true
Ban_On_Mention_Number: 4
#
#
#Chat
URL_Broadcast: false
Role_Admins:
- Owner
- Co-Owner
- "Server Admin"
Role_Colors:
  Active Level 1: f1c40f
  Active Level 2: f1c40f
  Active Level 3: f1c40f
  Co-Owner: 1bae93
  Purple: 8a00ff
  Member: 7289da
  Most Active: f1c40f
  Owner: fbff00
  Server Admin: ba3e39
Channels_Receive:
- general
- default
- news
- minecraft
- voice-chat
- other
Channels_Send:
- general
- minecraft
- suggestions
- voice-chat
- other
- botspam
Default_Channel: minecraft
#
#
#Commands
CMD_Enable: true
#php CMD_Command_Prefix: "^([?!@#%*/.$,=]+)?[Cc][Hh](?(1)(?:(?1)|[\\s]?)|(?1)+)"
CMD_Command_Prefix: ^(?:[?!@#%*/.$,=]+[Cc][Hh](?!$)[?!@#%*/.$,=]*|[Cc][Hh][?!@#%*/.$,=]+)
CMD_Channels_Receive:
- general
- default
- off-topic
- minecraft
- voice-chat
- other
- botspam
CMD_Channels_Send:
- general
- minecraft
CMD_Default_Channel: botspam
Fake_Admin_Role: 123456
Fake_Admin_Rolename: "Super Admin"
#
#
#Voice Chat
VC_Options:
  # Type your Voice Channel's ID here: 
  987654321:
# Voice Chat Accompanying text channel ID. (Right click channel, Copy ID)
# This channel will have the ping message placed here.
# If you are using the built in text channel, use the same ID as your voice channel.
    VC_Text_Channel_ID: 123456789
# Voice Chat Role's ID. (Mention role in a message with a \ before the mention to get the ID)
# This is the role to ping to notify other fellow chatters to come chat.
    VC_Role_ID: 123
# Voice Chat Role name. Case sensitive!
# This is the role to ping to notify other fellow chatters to come chat.
    VC_Role_Name: VC
# Voice Chat Channel's ID. (Right click channel, Copy ID)
    # VC_Channel_ID: 987654321
# Voice Chat Channel's name. Case sensitive!
    # VC_Channel_Name: General
# Ping Timeout
# How long (in milliseconds) should we wait before performing another ping?
# Default: 12 hours = 43200000
    VC_Ping_Timeout: 43200000
    VC_Ping_If_Role_Member: true
    VC_Ping_Min_Member: 2
# Ping Message
# What should we say to the Discord members?
    VC_Ping_Message: "What's up fellow %RoleID%? Come join %UserID% in the %Channel% channel!"
# What should we say to the Minecraft server players?
    VC_Ping_Message_MC: "%User% is ready to voice chat on the Discord!!"
# What should we say to thank all the users who chatted in completed VC call??
    VC_DM_Thanks: false
# DM the VC ping role users?
    VC_DM_VC_Role: false
    VC_DM_Thanks_Message: "Thanks %User% for joining the voice chat today! See you again soon next time we are online and chatting!"
#
#
# Discord New Member welcome
# Welcome Message channel. Case sensitive!
# This channel will have the Welcome message placed here.
Welcome_Text_Channel_Name: general
# Voice Chat text Channel ID. (Right click channel, Copy ID)
Welcome_Text_Channel_ID: 123456789
# What roles, if any, do new joins need to be equipped with?
# Only role IDs are supported.
Welcome_Roles_Award: false
Welcome_Roles:
- 123
- 456
# If a previous member rejoins, restore their roles they had?
Welcome_Roles_Restore: true
# Ping Timeout
# How long (in milliseconds) should we wait before we don't delete the welcome message on new joiner's leave?
# Default: 4 days hours = 345600000
Welcome_Message_Timeout: 345600000
# What should we say to the new Discord members?
Welcome_Send_Message: true
Welcome_Message: "Welcome %UserID% to *our server*! \n Come introduce yourself by chatting below."
# What should we DM the new Discord member?
Welcome_Send_DM: false
Welcome_DM_Message: "Welcome to *our server*! \n\n We would like to get to know you! Come introduce yourself in the %WelcomeChannel% channel."
#
#
# Leaderboards
LB_Enable: true
LB_Options:
  Guild_Name: test123
  XP_Type: 1
  XP_Per_Message:
  - 15
  - 25
  XP_Gain_Rate: 1
  Role_Rewards:
    1:
      RoleID: 123
      RoleName: Newbie
    10:
      RoleID: 234
      RoleName: "Active Level 1"
    20:
      RoleID: 345
      RoleName: "Active Level 2"
    30:
      RoleID: 456
      RoleName: "Active Level 3"
    50:
      RoleID: 567
      RoleName: "Most Active"
    5:
      RoleID: 678
      RoleName: Member
  Stack_Role_Rewards: false
  Remove_On_Leave: true
  Level_Up_Message: "%UserID% just leveled up to %Level%"
# Set to true for current channel, false to disable, log to send to log channel, dm to dm user instead
  Level_Up_Announce: true
# Start annoucing when level reaches this start threshold
  Level_Up_Announce_Start: 0
  Level_Up_Announce_End: 50
#Only announce Level up if includes a Role Rewards Rank change
  Level_Up_Announce_OnlyReward: true
  NoXP_Channels:
  - 'botspam'
  - 'join-log'
  NoXP_RoleID:
  - 123
  - 456