# Welcome Message channel. Case sensitive!
# This channel will have the Welcome message placed here.
# Note: CHDiscord does not support threads or other special channel types at this time.
Welcome_Text_Channel_Name: general
# Voice Chat text Channel ID. (Right click channel, Copy ID)
Welcome_Text_Channel_ID: 123456789
# What roles, if any, do new joins need to be equipped with?
Welcome_Roles:
- 123
- 456
# Ping Timeout
# How long (in milliseconds) should we wait before we don't delete the welcome message on new joiner's leave?
# Default: 4 days hours = 345600000
Welcome_Message_Timeout: 345600000
# What should we say to the new Discord members?
Welcome_Message: "Welcome %UserID% to *our server*! \n Come introduce yourself by chatting below."
# What should we DM the new Discord member?
Send_Welcome_DM: false
Welcome_DM_Message: "Welcome to *our server*! \n\n We would like to get to know you! Come introduce yourself in the %WelcomeChannel% channel."