# Voice Chat Accompanying text channel name. Case sensitive!
# This channel will have the ping message placed here.
# Note: CHDiscord does not support threads or other special channel types at this time.
VC_Text_Channel_Name: voice-chat
# Voice Chat text Channel ID. (Right click channel, Copy ID)
VC_Text_Channel_ID: 123456789
# Voice Chat Role's ID. (Mention role in a message with a \ before the mention to get the ID)
# This is the role to ping to notify other fellow chatters to come chat.
VC_Role_ID: 123
# Voice Chat Role name. Case sensitive!
# This is the role to ping to notify other fellow chatters to come chat.
VC_Role_Name: VC
# Voice Chat Channel's ID. (Right click channel, Copy ID)
VC_Channel_ID: 987654321
# Voice Chat Channel's name. Case sensitive!
VC_Channel_Name: General
# Ping Timeout
# How long (in milliseconds) should we wait before performing another ping?
# Default: 12 hours = 43200000
VC_Ping_Timeout: 43200000
# Ping Message
# What should we say to the Discord members?
VC_Ping_Message: "%RoleID% %UserID% is ready to voice chat in the %Channel% channel! Come join for another fun time talking with your fellow members!"
# What should we say to the Minecraft server players?
VC_Ping_Message_MC: "%User% is ready to voice chat in the %Channel% channel! Come join the Discord server for another fun time talking with your fellow members!"
# What should we say to thank all the users who chatted in completed VC call??
VC_DM_Thanks: false
# DM the VC ping role users?
VC_DM_VC_Role: false
VC_DM_Thanks_Message: "Hey, I just want to say Thanks for joining the voice chat today! See you again soon next time we are online and chatting!"