advancement_trophy:
  story/root: b
  story/upgrade_tools: b
  story/smelt_iron: b
  story/obtain_armor: b
  story/mine_diamond: b
  story/enter_the_nether: b
  story/cure_zombie_villager: g
  story/enter_the_end: g
  nether/return_to_sender: s
  nether/distract_piglin: s
  nether/netherite_armor: g
  nether/explore_nether: s
  nether/summon_wither: b
  nether/brew_potion: b
  nether/create_full_beacon: g
  end/root: g
  end/kill_dragon: g
  end/respawn_dragon: s
  end/dragon_breath: s
  adventure/honey_block_slide: s
  adventure/fall_from_world_height: g
  adventure/avoid_vibration: b
  adventure/totem_of_undying: s
  adventure/summon_iron_golem: b
  adventure/trade_at_world_height: s
  adventure/trim_with_all_exclusive_armor_patterns: g
  adventure/adventuring_time: s
  adventure/play_jukebox_in_meadows: b
  adventure/sniper_duel: b
  adventure/bullseye: b
  adventure/overoverkill: s
  husbandry/root: b
  husbandry/place_dried_ghast_in_water: s
  husbandry/safely_harvest_honey: b
  husbandry/breed_an_animal: b
  husbandry/ride_a_boat_with_a_goat: b
  husbandry/tame_an_animal: b
  husbandry/silk_touch_nest: s
  husbandry/allay_deliver_cake_to_note_block: b
  husbandry/tactical_fishing: b
  husbandry/wax_on: s
  husbandry/wax_off: s
  husbandry/froglights: g
  husbandry/plant_any_sniffer_seed: b