### Bot Administration
# Config version number
v: 11
# - CommandHelper profile name in which your Discord Bot token is stored:
Profile_Name: discordCredentials
# Your Bot's information:
Bot_ID: 1000000
Bot_Name: bot
Log_Channel: bot-logs
# Which server should your bot primarly listen to? This server will have extra functionality related to your Minecraft server.
Primary_Guild: 2313
URL_Broadcast: true
# Autosave:
# Wait how long (in ms) between each autosave of certain database keys?
AutoSave_Wait: 600000
# Bot Activity:
Set_Activity: true
# - Accepted types: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM_STATUS, or COMPETING
Activity_Type: PLAYING
Activity_Message: Minecraft
#
#
# Mentions
Allowed_Mentions:
# - Select from: USER, ROLE, EVERYONE
- "USER"
- "ROLE"
#
#
# Message Caches:
# (Kept in RAM for reference in various bot functions)
# - How many days (expressed in milliseconds) to keep a message in cache? (default / max: 30 days)
Msg_Cache_Time: 2592000000
# - How many messages of each type to keep?
Msg_Cache_Server: 5000
Msg_Cache_Cmd: 250
#
# Command System:
# - List blacklisted commands across the entire bot below:
CMD_Blacklist_Commands:
  - p
  - skip
  - pause
  - queue
  - stop
  - play
  - trade
  - t
#
#
# Leaderboard Global options:
# Path to webserver to publish Leaderboard jsons
LB_Web_Path: "/var/www/html/"
# What server's leaderboard should be the default to load? **Requires numeric ID**
LB_Web_Load_ID: 123456
#
#
# Default System Messages
# If a server does not specify a message in their config, the default listed here is used.
#Member Joins and Leaves
Log_Messages_Member_Join: ":join: **%User%**  [%UserID%] joined using invite **%InviteCode%** %PrevJoins%\n `Invite: -Use #%Uses%  -From: %Inviter% %InviterID%`"
Log_Messages_Member_Leave: ":leave: **%User%** left the server. `%Level% %PrevJoins% %Inviter%`"
#General Alert to all server members. Useful to tell users to keep their accounts safe, and to inform users of why many channels may have missing unread messages.
#Leave blank to disable sending an announcement
AS_General_Announcement: "oof a member got hacked and spammed the same message a lot. I've removed those messages; sorry for the unread notifications!\nRemember if you get your account back feel free to DM one of us or someone from the server so that you can be unbanned."
# Showcase Channel
# What replies should we say to users who were chatting?
Showcase_Reactions:
  # Chat was not allowed, as it did not fit the posting requirements
  Not_Allowed: "To show your cool project please include a picture!\n To react, add a reaction and talk in %TalkChannel%"
  # Previous message already is a comment from same poster
  Multiple_Msgs: "%UserID% To include more details about your project please edit the additional info into your previous post."
  # Chat was a reaction from another user
  Reaction_Comment: "Thanks for your comment %UserID%! To avoid chat in the showcases, **add a reaction** to the original post and **talk in %TalkChannel%** about the showcased project!"
#
#
  