# General Bot Administration
# - CommandHelper profile name in which your Discord Bot token is stored:
Profile_Name: discordCredentials
# Your Bot's information:
Bot_ID: 1000000
Bot_Name: bot
Log_Channel: bot-logs
# Which server should your bot primarly listen to? This server will have extra functionality related to your Minecraft server.
Primary_Guild: 2313
URL_Broadcast: true
# Autosave:
# Wait how long (in ms) between each autosave of certain database keys?
AutoSave_Wait: 600000
# Bot Activity:
Set_Activity: true
# - Accepted types: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM_STATUS, or COMPETING
Activity_Type: PLAYING
Activity_Message: Minecraft
#
#
# Mentions
Allowed_Mentions:
# - Select from: USER, ROLE, EVERYONE
- "USER"
- "ROLE"
#
#
# Message Caches:
# - How many message of each type to keep in RAM for reference in various bot functions?
Msg_Cache_User: 500
Msg_Cache_Server: 1000
Msg_Cache_Cmd: 250
#
# Command System:
# - List blacklisted commands across the entire bot below:
CMD_Blacklist_Commands:
  - p
  - skip
  - pause
  - queue
  - stop
  - play