# General admin
Profile_Name: discordCredentials
Bot_ID: 1000000
Bot_Name: bot
Log_Channel: bot-logs
Primary_Guild: 2313
URL_Broadcast: true
# Accepted types: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM_STATUS, or COMPETING
Activity_Type: PLAYING
Activity_Message: Minecraft
#
#
# Mentions
Allowed_Mentions:
# Select from: USER, ROLE, EVERYONE
- "USER"
- "ROLE"